### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by sirfak** [typestack/routing-controllers#504] opened 2019-08-03 11:58 UTC
Is this project abandoned?

**Comment by georgyfarniev** [comment] 2019-08-03 12:00
@sirfak yes, this project is inactive. Take a look at https://github.com/iyobo/koa-ts-controllers if you using koa.

**Comment by GabeKuslansky** [comment] 2019-08-07 20:58
Best alternative for express?

**Comment by jotamorais** [comment] 2019-08-07 22:04
> Is this project abandoned?

If it's abandoned, I would be willing to help maintain it moving forward.

**Comment by georgyfarniev** [comment] 2019-08-07 22:42
@jotamorais the problem is that owner is very busy for review pull requests. @pleerock how about providing access for other maintainers to support this project if you cannot keep working on it? I think the only problem here could be the trust

**Comment by jotamorais** [comment] 2019-08-08 00:15
> @jotamorais the problem is that owner is very busy for review pull requests. @pleerock how about providing access for other maintainers to support this project if you cannot keep working on it? I think the only problem here could be the trust

I agree with the part "trust" - but that can be solved by granting permission to 2 or 3 (can collectively discuss/evaluate/approve).

**Comment by rustamwin** [comment] 2019-08-08 06:57
> the problem is that owner is very busy for review pull requests. @pleerock how about providing access for other maintainers to support this project if you cannot keep working on it? I think the only problem here could be the trust

@pleerock was left the project,  now @NoNameProvided and @19majkel94 maintainers the project

**Comment by sirfak** [comment] 2019-08-09 07:09
With new maintainers, do we have hope that this wonderful project is alive?

**Comment by cdeutsch** [comment] 2019-08-16 15:56
Just tried this out and it looks great! But I'm stuck on #422.

There hasn't been a new commit in over a year (that's a dead project in my book)

If someone, @jotamorais is willing to maintain it, I'd say just fork it since the current owners haven't responded.

**Comment by jotamorais** [comment] 2019-08-16 21:25
> Just tried this out and it looks great! But I'm stuck on #422.
> 
> There hasn't been a new commit in over a year (that's a dead project in my book)
> 
> If someone, @jotamorais is willing to maintain it, I'd say just fork it since the current owners haven't responded.

I'm really keen to help in maintaining moving forward but would be good to get current owners agreement/acknowledgment and try to align some of their previous ideas, such as the [initial  backlog](https://github.com/typestack/routing-controllers/issues/333#issue-276620612)

**Comment by CupCakeArmy** [comment] 2019-08-30 22:03
Please don't make this die. I would be willing to help out to keep it alive!

**Comment by CupCakeArmy** [comment] 2019-09-01 15:19
Are @NoNameProvided and @MichalLytek the project maintainers? This seems like a dead end to me if it's even impossible to reply to thread about the feature of the project. Would be a pity since the code is really good and it would be stupid to just run it into the ground like this.
Worst case we could create a fork with maintainers that are willing to put the time in and continue form there.
What do you think @jotamorais ?

**Comment by jotamorais** [comment] 2019-09-01 19:06
> Are @NoNameProvided and @MichalLytek the project maintainers? This seems like a dead end to me if it's even impossible to reply to thread about the feature of the project. Would be a pity since the code is really good and it would be stupid to just run it into the ground like this.
> Worst case we could create a fork with maintainers that are willing to put the time in and continue form there.
> What do you think @jotamorais ?

I'm down and can certainly help to maintain this project with other interested parts on moving it forward.

**Comment by CupCakeArmy** [comment] 2019-09-01 19:29
Ok I think it's fair to give one week to @NoNameProvided and @MichalLytek to give input/feedback on this. Otherwise I'd suggest we fork. I don't have much experience with the whole reflection metadata thing in typescript. I know some base concepts but I guess it will be learning by doing.

**Comment by MichalLytek** [comment] 2019-09-01 19:38
If you want to maintain the project, just ask @pleerock to get access to the typestack team and work on routing-controllers like @vlapo on class-validator.

**Comment by jotamorais** [comment] 2019-09-19 15:13
> If you want to maintain the project, just ask @pleerock to get access to the typestack team and work on routing-controllers like @vlapo on class-validator.

@pleerock would you grant me access to TypeStack to work with the community on open issues and review/accept PRs, etc?

Thank you!

**Comment by MichalLytek** [comment] 2019-09-20 07:15
@jotamorais 
You have to mail him at pleerock.me@gmail.com, he has 1000+ notification on github per month.

**Comment by jotamorais** [comment] 2019-09-20 15:04
> @jotamorais
> You have to mail him at [pleerock.me@gmail.com](mailto:pleerock.me@gmail.com), he has 1000+ notification on github per month.

Thanks @MichalLytek. E-mail sent!

**Comment by pleerock** [comment] 2019-09-20 18:26
@jotamorais done. Take it with responsibility please :)

**Comment by jotamorais** [comment] 2019-09-20 20:40
> @jotamorais done. Take it with responsibility please :)

Thanks, @pleerock!

Calling the community now to come up with a list of priorities for the issues and new features. Also, to contribute with PRs.

I thought of starting and prioritize all issues labeled [`bug`](https://github.com/typestack/routing-controllers/issues?q=is%3Aopen+is%3Aissue+label%3Abug), but I'm not sure how accurate and those labels are at the moment and how/when the triage was done.

**Comment by georgyfarniev** [comment] 2019-09-20 23:29
@jotamorais yay this project will get maintained finally. Thank you. Welcome

**Comment by gstamac** [comment] 2019-09-23 09:28
@jotamorais great news you managed to become a maintainer. I would suggest you start with open PRs.

**Comment by consense** [comment] 2019-09-30 18:47
Unfortunately don't have the time for prolonged PR reviews currently, but could at least help by labeling current issue backlog if you need any help @jotamorais

**Comment by jotamorais** [comment] 2019-09-30 18:54
> Unfortunately don't have the time for prolonged PR reviews currently, but could at least help by labeling current issue backlog if you need any help @jotamorais

Yeah, that would be a great help, @consense 
It's a bit overwhelming right now, to go through all issues, open PRs and also plan new futures and new releases.

I'm about to integrate [PR#315](https://github.com/typestack/routing-controllers/pull/315) and [PR#512](https://github.com/typestack/routing-controllers/pull/512) in preparation for the 1st major release in a long time.
I'm integrating onto the `next` branch and from there will merge onto master to release the new version on the package (0.8.0) with breaking changes.

**Comment by jotamorais** [comment] 2019-09-30 20:57
@NoNameProvided, can you help to review the master branch and if you're okay with, package and publish it to NPM (or grant me access to publish)?

Thank you!

**Comment by elthrasher** [comment] 2019-10-01 11:57
@jotamorais The glitter chat referenced in the README is still active. Maybe it would make sense to set up a slack? I'm up for some more tasks to keep this project alive. I spent some time looking at alternatives, but this lib really hits the sweet spot between being great to use and being non-opinionated (like express).

I can try running some more tests against master and I think the changelog needs some additions, so I'll open a PR for that.

**Comment by jotamorais** [comment] 2019-10-01 14:49
@elthrasher I vote to keep the [Gitter](https://gitter.im/typestack/routing-controllers) channel.
I will drop a line there and will be monitoring it on a daily basis.

By the way, I accepted the PR for the changelog.

Thanks!

**Closed by jotamorais** 2019-10-01 14:49 UTC
