### ISSUE TITLE
Strange problem with query param

### ISSUE THREAD

**Issue by TKul6** [typestack/routing-controllers#370] opened 2018-02-14 17:00 UTC
Hi,
I'm, having a strange problem when I need to send a string parameter in the query param section.
If i use the following code:
```typescript
 @QueryParam('term')term= ''
```

I get an Error and the app return 404

But when I add the parameter type, everything works fine
```typescript
 @QueryParam('term')term :string = ''
```

What do I do wrong?

**Comment by 19majkel94** [comment] 2018-02-14 17:14
AFAIK, params are normalized so there might be a bug when you don't annotate it with type.

**Comment by TMaster** [comment] 2018-02-14 19:25
I check other places in my code and this phenomena happen there too. 
Just by requesting a string parameter without defining the parameter as string.
Is there any more information you wish to know?

Thanks,

**Comment by cxcorp** [comment] 2018-02-22 16:39
I just run into a similar issue myself. I did some digging and found that this is caused by how TypeScript emits metadata with `emitDecoratorMetadata`. [Only explicit types are serialized](https://github.com/Microsoft/TypeScript/issues/18995). This means that if your parameter's type is inferred by the compiler implicitly, it will be marked as an `Object` instead of the correct inferred type.

I also found that [using union types causes the type to be emitted as `Object`](https://github.com/Microsoft/TypeScript/issues/14971#issuecomment-337636381) (so even `string | undefined` or `number | null` become `Object`). Whether this is intended behaviour or a bug...no clue.

Due to this, your string parameter gets parsed as if the parameter's type was a class or an interface because when parsing the parameters, `routing-controllers` [only sees the _emitted type name_](https://github.com/typestack/routing-controllers/blob/11574d640724263738a0f30c5bf79067a99b7c01/src/ActionParameterHandler.ts#L110) (which is now `object` instead of `string` like it should be). As such, it attempts to [parse the string as JSON](https://github.com/typestack/routing-controllers/blob/11574d640724263738a0f30c5bf79067a99b7c01/src/ActionParameterHandler.ts#L137) which fails because you probably don't happen to be passing JSON via the query parameter.

So @19majkel94's intuition was very much correct. I think that this should be mentioned somewhere in the documentation because it certainly isn't an obvious cause.

**Closed** 2020-02-19 00:00 UTC
Labels: bug, needs more info, no-issue-activity, type: docs
