### ISSUE TITLE
fix: routes from imported controllers via directory return 404 in 0.10.0

### ISSUE THREAD

**Issue by dbrewer5** [typestack/routing-controllers#980] opened 2023-01-04 19:54 UTC
### Description
It seems that using the directory-based import as described in the documentation does not work after upgrading to v0.10.0. Falling back to directly registering each controller works as intended. This applies when setting both, controllers and middleware.

**Minimal code-snippet showcasing the problem**
```ts
import { createKoaServer } from 'routing-controllers'
import { join } from 'path'

const app = createKoaServer({
    controllers: [join(__dirname, '/controllers/*.*s')],
    middleware: [join(__dirname, '/middleware/*.*s')]
})

app.listen(3000) // all routes will return 404 and middleware will be ignored
```

### Expected behavior
Should keep working as it did in v0.9.0. 

### Actual behavior
All routes associated with registered controllers return 404 and middleware is ignored.

**Comment by attilaorosz** [comment] 2023-01-04 20:32
Does not found mean it returns 404 or the modules themselves are not found when starting the app?

**Comment by dbrewer5** [comment] 2023-01-04 20:34
> Does not found mean it returns 404 or the modules themselves are not found when starting the app?

All routes return 404. I've updated the issue to reflect that correctly.

**Comment by attilaorosz** [comment] 2023-01-04 20:42
Could you please provide a bit more info? I cannot reproduce this locally.

**Comment by jcrka** [comment] 2023-01-10 20:11
Are you on windows ?
May be this is the same ?  https://github.com/typestack/routing-controllers/issues/987

**Comment by Apperk274** [comment] 2023-01-23 09:22
Still does not work on Windows after fix #994

**Comment by attilaorosz** [comment] 2023-01-23 09:56
Have you tried locally? This is not released yet I guess.

**Comment by Apperk274** [comment] 2023-01-23 11:22
Oh sorry, I thought it was in 0.10.1 release. My bad

**Comment by attilaorosz** [comment] 2023-03-06 20:57
Should be released. Please close this issue if it works for you or add a comment if not.

**Comment by attilaorosz** [comment] 2023-04-15 05:19
Closing as complete, please reopen if you find an issue.

**Closed by attilaorosz** 2023-04-15 05:19 UTC
Labels: type: fix, status: needs triage
