### ISSUE TITLE
@HttpCode doesnt return the correct Status code

### ISSUE THREAD

**Issue by Abdullah8006** [typestack/routing-controllers#1098] opened 2023-04-07 09:54 UTC
### Description

**Minimal code-snippet showcasing the problem**
 

The following controller action simply returns an array. The controller action works fine but the `@HttpCode` doesn't return the 201 code but 200 (screenshot 2).
```ts
@Post()
@HttpCode(201)
public async createCampaign(
    @HeaderParam('x-partner-id', { required: true }) partnerId: string,
    // @Body() request: CheckPointTemplate, 
    @Res() response: express.Response): Promise<express.Response> {
    console.log(`Creating the campaing ${this.checkPointTemplateService}`);

    const test = [
        {
            name: 'abd',
            age: 34
        },
        {
            name: 'Inam',
            age: 32
        }
    ]
    
    //return response.json(test); --> This also doesn't work
    return response.json(test).send();
}

```

![image](https://user-images.githubusercontent.com/6733980/230588017-a359f065-3e47-4991-bbf8-fcd0365ad6c4.png)

### Expected behavior

The response should be returned with 201 status code.
### Actual behavior

The response returns with 200 status code.

**Comment by ElPerenza** [comment] 2023-04-14 22:08
I think this is intended behavior, as the [documentation states](https://github.com/typestack/routing-controllers#using-request-and-response-objects) that returning the `Response` object from a controller action is basically saying to the framework "don't worry, I already handled the reponse by myself". Not only `@HttpCode`, but all action decorators that modify the response (`@Header, @ContentType, @Location, @Redirect, @Render`) don't work when you return the `Response` object.

**Comment by attilaorosz** [comment] 2023-04-27 22:12
As @ElPerenza mentioned, this is working as intended. Closing.

**Closed by attilaorosz** 2023-04-27 22:12 UTC
Labels: type: fix, status: needs triage
