### ISSUE TITLE
Broken HttpError

### ISSUE THREAD

**Issue by dioio-io** [typestack/routing-controllers#532] opened 2020-01-23 11:41 UTC
System:

> node: v12.9.1
> npm: 6.10.2
> typescript: 3.7.5

index.ts
```ts
import 'reflect-metadata';
import { createExpressServer } from 'routing-controllers';

const app = createExpressServer({
  controllers: [__dirname + '/**/*.controller.js'], // even if reflection isn't used and the Controller is imported directly it doesn't work
});
app.listen(3000);

```

example/example.controller.ts
```ts
import { Controller, NotFoundError, Get } from "routing-controllers";

@Controller('/example')
export class ExampleController {
  @Get()
  public get(): string {
    throw new NotFoundError('what!');
  }
}
```

Causes the following error to be produced
```
Error at NotFoundError.HttpError [as constructor] (/Users/john.doe/Documents/code/routing-controllers/node_modules/routing-controllers/http-error/HttpError.js:30:23) at new NotFoundError (/Users/john.doe/Documents/code/routing-controllers/node_modules/routing-controllers/http-error/NotFoundError.js:23:28) at ExampleController.get (/Users/john.doe/Documents/code/routing-controllers/dist/example/example.controller.js:17:15) at ActionMetadata.callMethod (/Users/john.doe/Documents/code/routing-controllers/node_modules/routing-controllers/metadata/ActionMetadata.js:108:48) at /Users/john.doe/Documents/code/routing-controllers/node_modules/routing-controllers/RoutingControllers.js:99:140 at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

According to the documentation I should expect 
```json
{
  "name": "NotFoundError",
  "message": "what!"
}
```

**Comment by ahmedabdelhafez** [comment] 2020-03-01 16:23
i have the same issue too

**Comment by marines** [comment] 2020-04-09 17:23
same

**Comment by franckbattu** [comment] 2020-04-27 20:54
same issue

**Comment by jotamorais** [comment] 2020-05-01 06:31
@dioio-io, @ahmedabdelhafez, @marines, @franckbattu this is expected behavior when NODE_ENV is not production.

> (property) RoutingControllersOptions.development?: boolean
> Indicates if development mode is enabled. By default, it's enabled if your NODE_ENV is not equal to "production".
> 

To test locally, you set the `development` property of `RoutingControllersOptions`, to false.

I've created [this sandbox](https://codesandbox.io/s/routing-controller-broken-httperror-532-lmmg5?file=/README.md) to show.

Similar: #473, #460, #440,

**Comment by devmattrick** [comment] 2020-05-07 06:11
I can confirm that setting it to production does remove the stack trace, but instead of returning JSON like in the documentation, it simply sends the error message in plaintext.

It'd be good to either make the error responses return JSON or update the documentation to reflect this.

**Comment by jotamorais** [comment] 2020-05-29 00:46
> I can confirm that setting it to production does remove the stack trace, but instead of returning JSON like in the documentation, it simply sends the error message in plaintext.
> 
> It'd be good to either make the error responses return JSON or update the documentation to reflect this.
> 
> **Edit:** It seems like you need to use the `@JsonController` decorator instead of the `@Controller` decorator. Makes sense, my bad!

Correct. I will close this issue but feel free to open new issues, PRs, or send your comments and feedback.

**Closed by jotamorais** 2020-05-29 00:46 UTC
Labels: question

**Comment by NoNameProvided** [comment] 2020-08-09 10:18
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
