### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by coolirisroto** [typestack/routing-controllers#549] opened 2020-03-19 02:02 UTC
Version node 12.16.1
    "routing-controllers": "^0.8.0",

I have the next error:

(node:52631) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at loadFileClasses (/Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:17:20)
    at /Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:17:67
    at Array.forEach (<anonymous>)
    at loadFileClasses (/Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:17:35)
    at /Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:17:67
    at Array.forEach (<anonymous>)
    at loadFileClasses (/Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:17:35)
    at /Users/koco/Documents/proyectos/travel-selling-platform/hotels/Hotels/node_modules/routing-controllers/util/importClassesFromDirectories.js:14:52
    at Array.forEach (<anonymous>)
(node:52631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jotamorais** [comment] 2020-05-01 06:44
@coolirisroto can you please elaborate a bit more on what you're trying to do? It would be great if you could create a small reproduction of your problem.

You can use this sandbox template: https://codesandbox.io/s/routing-controllers-bug-fjgj3

**Comment by NoNameProvided** [comment] 2020-08-09 18:17
Closing as cannot reproduce as OP didn't answer.

**Closed by NoNameProvided** 2020-08-09 18:17 UTC
Labels: status: cannot reproduce, type: question
